---
- hosts: hostar
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: /usr/sbin/qm stop {{ redhat_id }} && sleep 5 && /usr/sbin/qm destroy {{ redhat_id }}
      register: result
      failed_when: result.rc != 1

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
