---
- name: Ping specific IP address from hostar
  hosts: myhosts
  gather_facts: false
  tasks:
    - name: Ping the IP address
      ansible.builtin.command:
        cmd: ping -c 4 158.174.87.156
      register: ping_output

    - name: Display ping result
      debug:
        var: ping_output.stdout
