---
- hosts: hostar
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /root/redhat
      register: result
      failed_when: result.rc != 1

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
